### ISSUE TITLE
在RecyclerView中使用ExpandableTextView时的问题

### ISSUE THREAD

**Issue by youyutongxue** [MZCretin/ExpandableTextView#10]
在RecyclerView中使用ExpandableTextView时，在有些手机上偶尔会出现白屏，加载不出内容的情况，稍微一滑动列表又立马出现内容，这种情况不是每次都出现，出现的概率3%左右。在锤子手机（5.1.1）、vivo手机上均出现过这种情况。

**Comment by MZCretin** [comment]
可以在出现问题的这些机型上测试下提供的demo.apk吗

**Comment by youyutongxue** [comment]
> 可以在出现问题的这些机型上测试下提供的demo.apk吗

可以可以

**Comment by colorchenvip** [comment]
这种情况很容易复现，弱网下（256kbps以下），百分之百必显，正常网络下可以正常。

**Comment by MZCretin** [comment]
已添加
