### ISSUE TITLE
文字收缩折叠遇到的问题

### ISSUE THREAD

**Issue by mtdhllf** [MZCretin/ExpandableTextView#12]
在RecyclerView,文字多时默认收缩状态,点击展开后,文字出现展开后又收缩现象,第一次点才会出现~

**Comment by MZCretin** [comment]
能否提供下效果图或者体验下demo 看是否有此问题

**Comment by mtdhllf** [comment]
添加了回调就会->展开折叠的回调,在RecyclerView中,其他情况不情况没试~
