### ISSUE TITLE
这个的确是不支持RecyclerView中使用，因为条目回收的原因

### ISSUE THREAD

**Issue by ImportEffort** [MZCretin/ExpandableTextView#2]
在recyclerView 条目中 中使用后，展开指定条目，待条目滑出屏幕后，会被回收。再次进入会变成收起状态。

**Comment by ImportEffort** [comment]
[效果](https://ws1.sinaimg.cn/large/006tNbRwly1fvfuezgiijg30f40qokjv.gif)

**Comment by MZCretin** [comment]
这个功能我会在下个版本处理下 @ImportEffort

**Comment by MZCretin** [comment]
@ImportEffort  1.3已经支持对当前状态保存的功能  [效果](https://github.com/MZCretin/ExpandableTextView/raw/master/extra/demo_gif.gif)
