### ISSUE TITLE
链接识别还有问题，像这样:这是一个测试网址，www.baidu.com，啦啦啦，会把前面的汉字和链接放到一起

### ISSUE THREAD

**Issue by dary123** [MZCretin/ExpandableTextView#23]
链接识别还有问题，像这样:这是一个测试网址，www.baidu.com，啦啦啦，会把前面的汉字和链接放到一起，必须在www前加上http://才会生效

**Comment by MZCretin** [comment]
这里链接的识别使用的是Android系统的链接正则去匹配的！

**Comment by dary123** [comment]
那怎么样才能识别是链接呢， 感觉这种匹配方式是有问题的

**Comment by dary123** [comment]
这是一个测试网址，hhtp://www.baidu.com，啦啦啦，像这样，又会把链接和后面的汉字结合到一起了，必须将逗号改成空格才行

**Comment by dary123** [comment]
个人用无所谓，但是我是给公司做的，这样硬性规定链接拼接的话，给后台编辑人员会造成一定的困扰

**Comment by MZCretin** [comment]
你不加空格 他怎么知道你的链接意图

**Comment by dary123** [comment]
必须是空格吗，其他符号不行么

**Comment by dary123** [comment]
这个其实问题不算太大，但是前面必须加http就比较麻烦了

**Comment by MZCretin** [comment]
普遍通用规定就是这样的

**Comment by MZCretin** [comment]
或者你想自定义一些规则 你可以修改源码中的正则来实现你自己的需求
