### ISSUE TITLE
1.5.3版本关于收回 展开点击事件

### ISSUE THREAD

**Issue by zhangqifan1** [MZCretin/ExpandableTextView#26]
setExpandOrContractClickListener 点不出来- -是不是去掉了啊- -

**Comment by MZCretin** [comment]
点不出来是什么意思 @zhangqifan1

**Comment by zhangqifan1** [comment]
![图片](https://user-images.githubusercontent.com/29973474/56861266-d8ecf500-69d1-11e9-9099-1e563b8f4b0a.png)

**Comment by zhangqifan1** [comment]
大佬,是不是我需要设置什么,这里掉不出来 展开 和 收回的 监听

**Comment by MZCretin** [comment]
你是不是给TextView设置了点击事件了 @zhangqifan1

**Comment by zhangqifan1** [comment]
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

/**
 *   正常的使用
 */
        ExpandableTextView expandableTextView = findViewById(R.id.expand_tv);
        //需要显示的内容
        String yourText = "  我所认识的中国，强大、友好。@奥特曼 “一带一路”经济带带动了沿线国家的经济发展，促进我国与他国的友好往来和贸易发展，可谓“双赢”。http://www.baidu.com 自古以来，中国以和平、友好的面孔示人。汉武帝派张骞出使西域，开辟丝绸之路，增进与西域各国的友好往来。http://www.baidu.com 胡麻、胡豆、香料等食材也随之传入中国，汇集于中华美食。@RNG 漠漠古道，驼铃阵阵，这条路奠定了“一带一路”的基础，让世界认识了中国。";
        //将内容设置给控件
        expandableTextView.setContent(yourText);
        //xml中的属性也可以通过代码设置 比如
        expandableTextView.setNeedExpend(true);
        //还有很多。。。。
        //添加点击监听
        expandableTextView.setLinkClickListener(new ExpandableTextView.OnLinkClickListener() {
            @Override
            public void onLinkClickListener(LinkType linkType, String content, String selfContent) {
                //根据类型去判断
                if (linkType.equals(LinkType.LINK_TYPE)) {
                    Toast.makeText(MainActivity.this, "你点击了链接 内容是：" + content, Toast.LENGTH_SHORT).show();
                } else if (linkType.equals(LinkType.MENTION_TYPE)) {
                    Toast.makeText(MainActivity.this, "你点击了@用户 内容是：" + content, Toast.LENGTH_SHORT).show();
                } else if (linkType.equals(LinkType.SELF)) {
                    Toast.makeText(MainActivity.this, "你点击了自定义规则 内容是：" + content + " " + selfContent, Toast.LENGTH_SHORT).show();
                }
            }
        });

        //添加展开和收回操作
        expandableTextView.setExpandOrContractClickListener(type -> {
            if (type.equals(StatusType.STATUS_CONTRACT)) {
                Toast.makeText(MainActivity.this, "收回操作", Toast.LENGTH_SHORT).show();
            } else {
                Toast.makeText(MainActivity.this, "展开操作", Toast.LENGTH_SHORT).show();
            }
        });

    }
}

**Comment by zhangqifan1** [comment]
就这些了 ...

**Comment by zhangqifan1** [comment]
![图片](https://user-images.githubusercontent.com/29973474/56861482-b1972780-69d3-11e9-818a-7d9710e9b1ea.png)

**Comment by MZCretin** [comment]
是点了没有弹toast吗
@zhangqifan1

**Comment by zhangqifan1** [comment]
不是,我没有这个方法啊,,

**Comment by zhangqifan1** [comment]
![图片](https://user-images.githubusercontent.com/29973474/56861585-dd66dd00-69d4-11e9-9771-06fe7a5c2a66.png)

**Comment by MZCretin** [comment]
好吧 我看下  @zhangqifan1

**Comment by MZCretin** [comment]
你可以用下1.5.2版本

**Comment by MZCretin** [comment]
我刚刚检查了下 是有的  你检查下你是不是版本弄错了 @zhangqifan1

**Comment by zhangqifan1** [comment]
大佬,1.5.2可以,你的1.5.3可以么?

**Comment by zhangqifan1** [comment]
我重启下studio吧

**Comment by MZCretin** [comment]
恩恩

**Comment by zhangqifan1** [comment]
哈哈,好了,可以了谢谢大佬

**Comment by zhangqifan1** [comment]
可以调出来了
