### ISSUE TITLE
获取是否有构成展开&收缩的条件

### ISSUE THREAD

**Issue by yaojunqi** [MZCretin/ExpandableTextView#27]
getExpandableLineCount()这个方法我获取的有的时候是0

我需要一个是否满足展开&收缩功能的一个状态值

getExpandableLineCount() > max_line  有时不成立

**Comment by MZCretin** [comment]
为0是因为此时控件还没有计算出来行数

**Comment by MZCretin** [comment]
@yaojunqi  刚刚更新了，看下
https://github.com/MZCretin/ExpandableTextView#%E6%96%B0%E7%89%B9%E6%80%A7%E9%A2%9D%E5%A4%96%E8%AF%B4%E6%98%8E

**Comment by yaojunqi** [comment]
谢谢大佬，谢谢大佬，
因为我们公司需求是如图这样的，所以我需要拿到那个状态，才可以动态设置那个全文的隐显
