### ISSUE TITLE
请问下，如何做到链接高亮并可点击响应，但是还是显示实际链接地址呢？

### ISSUE THREAD

**Issue by M2dL1fe** [MZCretin/ExpandableTextView#28]

**Comment by MZCretin** [comment]
@M2dL1fe 刚刚更新了，看下
https://github.com/MZCretin/ExpandableTextView#%E6%96%B0%E7%89%B9%E6%80%A7%E9%A2%9D%E5%A4%96%E8%AF%B4%E6%98%8E

**Comment by M2dL1fe** [comment]
Nice @RollCretin
