### ISSUE TITLE
自定义规则有时候会出现问题

### ISSUE THREAD

**Issue by pangyu646182805** [MZCretin/ExpandableTextView#29]
[悠悠4649](686) : https://m.baidu.com
[悠悠4649](686) : 好多好多的回电话。https://m.baidu.com。 好多好多和

自定义规则显示会出现问题

**Comment by MZCretin** [comment]
@pangyu646182805  
哪个版本

**Comment by pangyu646182805** [comment]
1.6.0
https://m.baidu.com/?tn=&from=1013755s#iact=wiseindex%2Ftabs%2Fnews%2Factivity%2Fnewsdetail%3D%257B%2522linkData%2522%253A%257B%2522name%2522%253A%2522iframe%252Fmib-iframe%2522%252C%2522id%2522%253A%  
这个链接地址也会解析错误

**Comment by MZCretin** [comment]
自定义规则显示会出现问题

你想显示成什么样的？你是怎么自定义的？

**Comment by pangyu646182805** [comment]
`[悠悠4649](https://www.baidu.com/) : https://m.baidu.com
[悠悠4649](https://www.baidu.com/) : 好多好多的回电话。https://m.baidu.com。 好多好多和`

demo替换成这个内容  自定义规则的高亮显示错误

**Comment by MZCretin** [comment]
只是demo没有对自定义规则的自定义内容做处理  你自己运行deme，把内容替换就能看到效果了

**Comment by MZCretin** [comment]
最新的demo 自定义规则的那个view已经支持替换自定义内容了
