### ISSUE TITLE
app:ep_contract_text,app:ep_expand_text属性无效

### ISSUE THREAD

**Issue by paulpaulzhang** [MZCretin/ExpandableTextView#3]
我设置了自定义的展开和收回的文案但实际显示还是默认的，是怎么回事？

**Comment by MZCretin** [comment]
尴尬 昨天更新的时候位置写错了 在v1.3.1中已修复
implementation 'com.github.MZCretin:ExpandableTextView:v1.3.1

**Comment by MZCretin** [comment]
@paulpaulzhang
