### ISSUE TITLE
不知道算不算是个问题

### ISSUE THREAD

**Issue by Jonniu** [MZCretin/ExpandableTextView#39]
部分手机APP安装后，app name 被替换成了ExpandableTextView

**Comment by Jonniu** [comment]
这是个非常严重的bug，无论是修改应用名的资源ID还是 replace label 都无法解决该问题

**Comment by Jonniu** [comment]
是英文配置的问题

**Comment by iostyle** [comment]
> 是英文配置的问题

遇到相同的问题，请问如何解决的呢？
