### ISSUE TITLE
你好，后期迭代 会考虑 会自由扩展 链接类型吗

### ISSUE THREAD

**Issue by zcm-hu** [MZCretin/ExpandableTextView#4]
例如：我所认识的中国，强大、友好。 “%{name}” 经济带动了沿线国家的经济发展，促进我国与他国的友好往来和贸易发展

自己去写规则匹配出 %{name}  并且设置展示的文案为"一带一路"

**Comment by MZCretin** [comment]
可以提供下应用场景吗？这个描述我不清楚怎么添加功能

**Comment by MZCretin** [comment]
你现在就是觉得只能对@用户 和 链接 进行高亮并添加点击不够用 想扩展其他的类似是吧 @zcm-hu

**Comment by zcm-hu** [comment]
是的

**Comment by MZCretin** [comment]
我正在考虑提供给调用者提供自定义的形式，但是方式有待确认，你所说的这种方式可能不行，后面我可能会按照markdown支持的形式提供接口支持。
```
比如下面这一段文字：
大家好，我是Cretin。
你想对Cretin进行高亮显示，那么你的原文应该是：
大家好，我是[Cretin](标识符)。
标识符可以是很多形式，如果你希望点击Cretin跳转网页，则标识符填链接；如果你想像你上面提到的，那么标识符可以填name，等等
```

**Comment by MZCretin** [comment]
具体形式有待考究，请你耐心等待，感谢您的意见

**Comment by zcm-hu** [comment]
👍

**Comment by MZCretin** [comment]
@zcm-hu 已经支持扩展自定义其他类型，详情请关注v1.4

**Comment by MZCretin** [comment]
@zcm-hu  可以去体验下
