### ISSUE TITLE
直接复制demo的完全没效果,请问是什么问题吗

### ISSUE THREAD

**Issue by crazyzjw** [MZCretin/ExpandableTextView#45]
`<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    tools:context=".ui.main.college.CollegeFragment">
    <com.ctetin.expandabletextviewlibrary.ExpandableTextView
        android:layout_marginTop="14dp"
        android:id="@+id/etv_item_content"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:lineSpacingExtra="4dp"
        android:textSize="14sp"
        android:text="dsjadashdahsjdhfhdsjfhjshdhfjsdhjfhsjdhfshdfjhjsddsjadashdahsjdhfhdsjfhjshdhfjsdhjfhsjdhfshdfjhjsddsjadashdahsjdhfhdsjfhjshdhfjsdhjfhsjdhfshdfjhjsddsjadashdahsjdhfhdsjfhjshdhfjsdhjfhsjdhfshdfjhjsddsjadashdahsjdhfhdsjfhjshdhfjsdhjfhsjdhfshdfjhjsddsjadashdahsjdhfhdsjfhjshdhfjsdhjfhsjdhfshdfjhjsddsjadashdahsjdhfhdsjfhjshdhfjsdhjfhsjdhfshdfjhjsddsjadashdahsjdhfhdsjfhjshdhfjsdhjfhsjdhfshdfjhjsddsjadashdahsjdhfhdsjfhjshdhfjsdhjfhsjdhfshdfjhjsd"
        android:textColor="@color/color_202828"
        app:ep_contract_color="@color/color_1C8E8E"
        app:ep_expand_color="@color/color_1C8E8E"
        app:ep_max_line="5"
        app:ep_need_animation="true"
        app:ep_need_always_showright="true"
        app:ep_expand_text="收起全文"
        app:ep_contract_text="展开全文"
        app:ep_need_contract="true"
        app:ep_need_expand="true" />

</FrameLayout>`

**Comment by MZCretin** [comment]
@crazyzjw 调用setContent方法才会生效
