### ISSUE TITLE
...添加问题

### ISSUE THREAD

**Issue by kevinStrange** [MZCretin/ExpandableTextView#5]
大佬，请教下如何在文本展开前面添加...这样的内容

**Comment by MZCretin** [comment]
lib已经处理过了，不需要你自己处理的

**Comment by kevinStrange** [comment]
我这边添加之后没有显示出效果出来

**Comment by MZCretin** [comment]
体验过demo了吗？demo可以正常显示吗？

**Comment by kevinStrange** [comment]
可以了，原来是被这个（“app:ep_need_always_showright="true"”）属性影响了
