### ISSUE TITLE
当文本内容有换行符时，展开、收起位置不在最右侧

### ISSUE THREAD

**Issue by 1378282082** [MZCretin/ExpandableTextView#8]
"太空碎片已成为一个严重的问题。据一家试图解决这个问题的公司负责人说，太空碎片在地球轨道上的积累已经成为一种障碍，并可能危及未来的月球或火星任务。\n\n更为糟糕的是，太空垃圾可以逗留几个世纪。虽然卫星最多只能维持10年左右的时间，但成为太空垃圾后停留的时间更长。太空垃圾只会在大气的阻力下缓慢地返回地球。\n\n";
![8ded01e92fbbc8d21c86f3db85e74d54](https://user-images.githubusercontent.com/19813879/46719178-c6d97e00-cc5c-11e8-8852-95fe7b7f1fff.jpg)
![d0ea26bf3117494fad08a55378b454fc](https://user-images.githubusercontent.com/19813879/46719179-c6d97e00-cc5c-11e8-825c-2f78364e71e9.jpg)

**Comment by MZCretin** [comment]
这个位置的计算受到很多因素的影响 很难做到准确到最后
